### PR TITLE
add sandeepk blog feed

### PR DESCRIPTION
**Pull request by Skchoudhary**

### CODE REVIEW

**Comment by jasonbraganza** [comment]
@Skchoudhary, fix whatever conflict here?

**Comment by Skchoudhary** [comment]
@jasonbraganza  done

**Comment by jasonbraganza** [comment]
@SaptakS this one too, please

**Comment by sayanchowdhury** [comment]
Seems like this still has conflicts.

**Comment by jasonbraganza** [comment]
it looks good to me. @Skchoudhary can you recheck anyway please?

**Comment by Skchoudhary** [comment]
It looks good to me also. But the only issue I see is that my blog feed entry is not the last one. Should I move my blog feed entry to last, or it's okay? @sayanchowdhury  @jasonbraganza

**Comment by SaptakS** [comment]
No need to move to the last. Can you just rebase on master and then push back? Rebasing and merging shows conflict.

**Comment by Skchoudhary** [comment]
@SaptakS  please have a look now

**Review by SaptakS — APPROVED** [review]
Looks good to me.

**Comment by jasonbraganza** [comment]
Yay!

**Pull request merged**
